package:
  name: pybind_bm3d
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: "{{ PYTHON }} -m pip install . -vv"

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - setuptools
    - bm3d=0.1.0
    - pybind11
    - fftw                      # Required for bm3d.h... (Even though statically linked..)
  run:
    - python
    - vs2015_runtime  # [win]
    - bm3d=0.1.0
    - pybind11

test:
  imports:
    - pybind_bm3d

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
